replicaCount: 1

image:
  repository: 471112631123.dkr.ecr.us-east-1.amazonaws.com/as-challenge-fran
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

# âœ… Agregado para evitar error por variable nil
ingress:
  enabled: false
  host: "localhost"  

resources: {}